builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}64-bit
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "darwin" }}apple
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - NOTICE*
      - LICENSE*
      - LICENCE*
      - README*
      - CHANGELOG*
