builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - NOTICE*
      - LICENSE*
      - LICENCE*
      - README*
      - CHANGELOG*
