name: goreleaser

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Echo Branch Name
        run: echo '${{ env.VERSION }}'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.3'
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
