name: goreleaser

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Branch Name
        run: echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Echo Branch Name
        run: echo '${{ env.branch_name }}'
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          find: "@@VERSION@@"
          replace: ${{ env.branch_name }}
          include: main.go
          regex: false
      - name: gitignore main.go after version injection
        run: echo "\nmain.go" >> .gitignore
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
